services:
  - type: web
    name: proyectoDjango
    env: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput

    startCommand: "gunicorn --workers 1 mi_sitio.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_sitio.settings
      - key: DATABASE_URL
        value: postgresql://proyectodjango_ojaa_user:i2laqK4UoZokda7LRTmQJw7NAdbLnHub@dpg-d4dsag8dl3ps73dj14jg-a.oregon-postgres.render.com/proyectodjango_ojaa