services:
  - type: web
    name: proyectoDjango
    env: python

    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput

    startCommand: "gunicorn --workers 1 mi_sitio.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_sitio.settings
      - key: DATABASE_URL
        value: postgresql://proyectomystictravel_user:K55PkZqCGGg0e2HbDbvaKA92XI5ZULfE@dpg-d4f108v5r7bs73cp1t00-a.oregon-postgres.render.com/proyectomystictravel