# Generated by Django 5.2.6 on 2025-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validacion', models.CharField(max_length=8)),
                ('usuario_creado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
