# Generated by Django 5.2.6 on 2025-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_usuariopermitido_contacto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermitido',
            name='codigo_validacion',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código de Validación'),
        ),
        migrations.AlterField(
            model_name='usuariopermitido',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre y Apellido'),
        ),
    ]
