# Generated by Django 5.2.6 on 2025-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_usuariopermitido_codigo_validacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopermitido',
            options={'verbose_name': 'Usuario Permitido', 'verbose_name_plural': 'Usuarios Permitidos'},
        ),
        migrations.AddField(
            model_name='usuariopermitido',
            name='debe_ser_staff',
            field=models.BooleanField(default=False, verbose_name='¿Debe ser Staff al registrarse?'),
        ),
    ]
