# Generated by Django 5.2.6 on 2025-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_usuariopermitido_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('titulo_principal', models.CharField(max_length=200, verbose_name='Título del Héroe (Banner Principal)')),
                ('cuerpo_seccion', models.TextField(verbose_name="Cuerpo de la Sección 'Acerca de Nosotros'")),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido del CMS',
                'verbose_name_plural': 'Contenidos del CMS',
            },
        ),
    ]
