"""
Django settings for mi_sitio project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
import ssl
import certifi

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9c51vz4&w6v1k)ey%tq6@l76^)g(f3mcz8vd3y1xk35xh3z*(+'
DEBUG = True
ALLOWED_HOSTS = ['proyectomystictravel.onrender.com', '127.0.0.1']
INSTALLED_APPS = []



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'landing',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mi_sitio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mi_sitio.wsgi.application'


import dj_database_url

DATABASES = {
'default': dj_database_url.config(
    default='postgresql://proyectomystictravel_user:K55PkZqCGGg0e2HbDbvaKA92XI5ZULfE@dpg-d4f108v5r7bs73cp1t00-a.oregon-postgres.render.com/proyectomystictravel',
    conn_max_age=600,
ssl_require=True
)
}


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True


STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'c2280296.ferozo.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'candela.godoy@lalupitacontenidos.site'
EMAIL_HOST_PASSWORD = 'Cande2025/'
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

DEFAULT_FROM_EMAIL = 'reservas@mysticaltravel.com'

EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
SSL_CERT_FILE = certifi.where()
ssl._create_default_https_context = ssl._create_unverified_context


MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

LOGIN_REDIRECT_URL = 'landing:dashboard'
LOGOUT_REDIRECT_URL = 'landing:login'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ]
}

IS_PROD = not DEBUG